version: "3.7"

services:
  app:
    image: tren_maya_app:latest  # Nombre específico para la imagen de la aplicación
    build:
      context: .
      dockerfile: Dockerfile
    container_name: API_tren_maya
    env_file: ./.env
    ports:
      - ${APP_LOCAL_PORT}:${APP_DOCKER_PORT}
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQLHOST: ${MYSQLHOST}
      MYSQLUSER: ${MYSQLUSER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQLDATABASE: ${MYSQLDATABASE}
    command: npm run start:prod